spring.application.name=strong-auth
spring.datasource.url=jdbc:postgresql://localhost:5432/strongauthdb
spring.datasource.username=postgres
spring.datasource.password=ZWEetg237!
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/school
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true